---
# Reference: https://medium.com/aws-activate-startup-blog/practical-vpc-design-8412e1a18dcc
- name: create a network stack
  amazon.aws.cloudformation:
    stack_name: "myNetworkStack"
    state: "present"
    region: "us-east-2"
    disable_rollback: true
    template: "roles/network/files/network_stack.yaml"
    tags:
      Stack: "ansible-cloudformation"