- name: Add Firewalld Rule
  shell: firewall-cmd --permanent --add-port=10250/tcp --add-port=30000-32767/tcp
  when: inventory_hostname in groups["nodes"]

- name: Reload Firewalld
  shell: firewall-cmd --reload
  when: inventory_hostname in groups["nodes"]
 
- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf
  when: inventory_hostname in groups["nodes"]

- name: Cluster Join Command
  shell: kubeadm token create --print-join-command
  register: JoinCluster
  when: inventory_hostname in groups["control_plane"]

- name: Join to cluster if needed
  shell: "{{ JoinCluster.stdout }}"
  when: inventory_hostname in groups["nodes"]
  become: True

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  when: inventory_hostname in groups["nodes"]
