---
#Reference: https://www.linuxtechi.com/how-to-install-kubernetes-cluster-rhel/

- include_tasks: cluster_infra.yaml
  when: awsStack == True

- include_tasks: shared.yaml
  when: awsStack == False

- include_tasks: configure-control_plane.yaml
  when: awsStack == False

- include_tasks: configure-worker_node.yaml
  when: awsStack == False