- name: Add Kubernetes Repo
  yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: 'https://pkgs.k8s.io/core:/stable:/v1.28/rpm/'
    enabled: True
    gpgcheck: True
    repo_gpgcheck: True
    gpgkey: 'https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key'
    exclude: 
      - kubelet 
      - kubeadm 
      - kubectl
      - cri-tools 
      - kubernetes-cni
  become: True

- name: Install Kubernetes
  yum:
    name:
      - kubeadm
    state: latest
    disable_excludes: kubernetes

- name: Disable system swap for Kubernetes
  shell: swapoff -a

- name: Remove current swaps from fstab permanently
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: yes
    state: present

- name: Load kernel modules
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '640'
    create: true
    line: "{{ item.line}}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { regexp: '^overlay', line: overlay}
    - { regexp: '^br_netfilter', line: br_netfilter}

- name: Add the overlay module
  community.general.modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Set IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true

- name: Pass bridged IPv4 traffic to iptable
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: true

- name: Pass bridged IPv6 traffic to iptable
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_set: true

- name: Apply kernel parameters
  shell: sysctl --system

- name: Install Kubernetes Runtime
  include_role:
    name: roles/crio

- name: Reload Kubelet
  systemd:
    name: kubelet
    enabled: True
    daemon_reload: True

- reboot:
