AWSTemplateFormatVersion: "2010-09-09"
Description: A template to create a network stack.
Parameters:
  SSHKeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: MY-VPC-v1
  