AWSTemplateFormatVersion: "2010-09-09"
Description: A template to create a network stack.
Parameters:
  SSHKeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: Name
        Value: MY-VPC-v1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.0/27
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: MY-PublicSubnet1-v1 
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.32/27
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: MY-PublicSubnet2-v1 
  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.64/27
      AvailabilityZone: "us-east-1c"
      Tags:
      - Key: Name
        Value: MY-PublicSubnet3-v1 
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.96/27
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: MY-PrivateSubnet1-v1 
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.128/27
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: MY-PrivateSubnet2-v1    
  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC
      CidrBlock: 10.0.0.160/27
      AvailabilityZone: "us-east-1c"
      Tags:
      - Key: Name
        Value: MY-PrivateSubnet3-v1    
