---
# tasks file for mongos
- name: Install MongoDB
  yum:
    name:
      - https://downloads.percona.com/downloads/percona-server-mongodb-6.0/percona-server-mongodb-6.0.14-11/binary/redhat/9/aarch64/percona-mongodb-mongosh-2.1.5.el9.aarch64.rpm
      - https://downloads.percona.com/downloads/percona-server-mongodb-6.0/percona-server-mongodb-6.0.14-11/binary/redhat/9/aarch64/percona-server-mongodb-mongos-6.0.14-11.el9.aarch64.rpm

- name: Add MongoS User and Group
  user:
    name: mongos

- name: Install MongoD SystemD Service
  copy:
    dest: /usr/lib/systemd/system/mongos.service
    src: mongos.service
    owner: root
    group: root

- name: Copy mongos conf file
  template:
    src: mongos.conf.j2  
    dest: /etc/mongos.conf
    owner: mongos
    group: mongos

- name: Create mongos log file
  file:
    path: /var/log/mongos.log
    owner: mongos
    group: mongos
    setype: mongod_log_t
    seuser: system_u
    serole: object_r
    state: touch

- name: Add mongos port to firewalld
  firewalld:
    port: 27017/tcp
    permanent: yes
    state: enabled

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: SystemD - Restart Mongos
  systemd:
    name: mongos
    enabled: True
    state: restarted
    daemon_reload: True