---
# tasks file for mongod
- name: Install MongoDB
  yum:
    name:
      - https://downloads.percona.com/downloads/percona-server-mongodb-6.0/percona-server-mongodb-6.0.14-11/binary/redhat/9/aarch64/percona-mongodb-mongosh-2.1.5.el9.aarch64.rpm
      - https://downloads.percona.com/downloads/percona-server-mongodb-6.0/percona-server-mongodb-6.0.14-11/binary/redhat/9/aarch64/percona-server-mongodb-server-6.0.14-11.el9.aarch64.rpm
    disable_gpg_check: True

- name: Add MongoS User and Group
  user:
    name: mongod

- name: Install MongoD SystemD Service
  copy:
    dest: /usr/lib/systemd/system/mongod.service
    src: mongod.service
    owner: root
    group: root

- name: Copy template file
  template:
    src: mongod.conf.j2  # Path to your Jinja2 template file
    dest: /etc/mongod.conf
    owner: mongod
    group: mongod

- name: Mongo Logging Permission
  file:
    path: /var/log/mongodb
    owner: mongod
    group: mongod
    setype: mongod_log_t
    seuser: system_u
    serole: object_r
    state: directory

- include_tasks: configure-cfgsvr.yaml
  when: inventory_hostname in groups["cfgsvrs"]

- include_tasks: configure-shard.yaml
  when: inventory_hostname in groups["shards"]

- name: SystemD - Start MongoDB now and at boot
  systemd:
    name: mongod
    enabled: True
    state: restarted
    daemon_reload: True