---
# Reference: https://github.com/cri-o/cri-o/blob/main/install.md#other-yum-based-operating-systems

- name: Add cri-o repo
  shell: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_9_Stream/devel:kubic:libcontainers:stable.repo
  shell: export OS=CentOS_9_Stream && export VERSION=1.28 && curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo

- name: Install crio
  ansible.builtin.yum:
    name: cri-o
    state: latest
    
# Configure crio

- name: Restart cri-o
  systemd:
    name: crio
    enabled: True
    daemon_reload: True
    state: restarted