---
# tasks file for crio
  - name: Add cri-o repo
    shell: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_9_Stream/devel:kubic:libcontainers:stable.repo && curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/CentOS_9_Stream/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo

- name: Install crio
  ansible.builtin.yum:
    name: cri-o
    state: latest
