---
# tasks file for crio
- name: Add cri-o repo
  shell: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo && curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24:/1.24.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.24:1.24.1.repo

- name: Install crio
  ansible.builtin.yum:
    name: cri-o
    state: latest
# Configure crio
# Restart crio